services:
  postgres:
    image: postgres:15
    container_name: service-courier-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: courier-db
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}'" ]
      interval: 10s
      timeout: 1s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - service-order-default


  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.26.0
    container_name: service-courier-migrations
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=${GOOSE_DRIVER}
      - GOOSE_DBSTRING=${GOOSE_DBSTRING}
    volumes:
      - ./migrations:/migrations
    networks:
      - service-order-default

  service-courier:
    image: pixik/courier-service:latest
    container_name: service-courier
    environment:
      - ENVIRONMENT=prod
    env_file:
      - .env
    ports:
      - 8082:${HTTP_PORT}
    restart: on-failure
    networks:
      - service-order-default
      - infrastructure_default
    depends_on:
      - postgres
      - migrations

networks:
  service-order-default:
    driver: bridge
  infrastructure_default:
    external: true

volumes:
  pgdata: