services:
  postgres:
    image: postgres:15
    container_name: service-courier-test-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: courier-test-db
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U tester -d test123'" ]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - local


  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.26.0
    container_name: service-courier-test-migrations
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://tester:test123@service-courier-test-db:5432/courier-test-db?sslmode=disable
    volumes:
      - ./migrations:/migrations
    networks:
      - local

networks:
  local:
    driver: bridge